### PR TITLE
Converted to .NET standard 2.0 project

### PR DESCRIPTION
**Pull request by gustafj**
Converted to .NET Standard 2.0 so that it is usable for .NET Core applications as well.
Tested and working as a nupkg with a .NET Core 2.0 application.

### CODE REVIEW

**Comment by gustafj** [comment]
Ping @brunurd .
This will make the package target a larger audience, since it will be compatible with both _Framework_ and _Core_.

**Comment by gustafj** [comment]
Ping @brunurd

**Comment by leonaaraujo** [comment]
Sorry @gustafj, I just see it now! I will consider.

**Comment by leonaaraujo** [comment]
I will make the next release with this standard, I just need first test in the Unity 4.6 .net framework version, or abandon Unity compatibility.

**Pull request merged**
